// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrgH2qoPhdmcUjzazc-RbcpkYuSW-WD48',
    appId: '1:694343437964:web:938fb266a62d52cefa35a9',
    messagingSenderId: '694343437964',
    projectId: 'revue-169b5',
    authDomain: 'revue-169b5.firebaseapp.com',
    storageBucket: 'revue-169b5.appspot.com',
    measurementId: 'G-14BCLET5T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_G0azWYVrWMT-ff6gppOtTgoGeizoVIY',
    appId: '1:694343437964:android:8947cdb5c583abf2fa35a9',
    messagingSenderId: '694343437964',
    projectId: 'revue-169b5',
    storageBucket: 'revue-169b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCX1Hl_GwU2KVnd66_I9-rVFaOO3zUOQ',
    appId: '1:694343437964:ios:ea39a6daa1940b93fa35a9',
    messagingSenderId: '694343437964',
    projectId: 'revue-169b5',
    storageBucket: 'revue-169b5.appspot.com',
    androidClientId: '694343437964-2jq5rep0vg2af391tl14gf94v2c6mq07.apps.googleusercontent.com',
    iosClientId: '694343437964-urid3n64k4hetv8j78dud4lk70m3kcjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gorevue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOCX1Hl_GwU2KVnd66_I9-rVFaOO3zUOQ',
    appId: '1:694343437964:ios:ea39a6daa1940b93fa35a9',
    messagingSenderId: '694343437964',
    projectId: 'revue-169b5',
    storageBucket: 'revue-169b5.appspot.com',
    androidClientId: '694343437964-2jq5rep0vg2af391tl14gf94v2c6mq07.apps.googleusercontent.com',
    iosClientId: '694343437964-urid3n64k4hetv8j78dud4lk70m3kcjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.gorevue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrgH2qoPhdmcUjzazc-RbcpkYuSW-WD48',
    appId: '1:694343437964:web:7c8326fd4f6cd25afa35a9',
    messagingSenderId: '694343437964',
    projectId: 'revue-169b5',
    authDomain: 'revue-169b5.firebaseapp.com',
    storageBucket: 'revue-169b5.appspot.com',
    measurementId: 'G-ELLZNCX74N',
  );
}
